import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout.js contains the UI for elements and contents that are common to a route
// segment and its children. This file eliminates the redundancy of
// having to repeat certain components or contents on every page of a segment and its descendants.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <section>
          {/* header */}
          <header>
            <nav></nav>
          </header>

          {children}

          {/* footer */}
          <footer></footer>
        </section>
      </body>
    </html>
  );
}
