import Link from "next/link";
import "./../../styles/global.css";
import Head from "./head";
// These styles apply to every route in the application
// import "./globals.css";

export const metadata = {
  title: "Create Next App : New in Next.js 13",
  description: "Generated by create next app",
};

// layout.js contains the UI for elements and contents that are common to a route
// segment and its children. This file eliminates the redundancy of
// having to repeat certain components or contents on every page of a segment and its descendants.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head />
      <body>
        {" "}
        <section>
          {/* header */}
          <header>
            <nav>TITLE PAGE</nav>
            <nav>
              <Link href={"./about"}>About</Link>
            </nav>
          </header>

          {children}

          {/* footer */}
          <footer></footer>
        </section>
      </body>
    </html>
  );
}
